# Generated by Django 3.2.3 on 2021-05-20 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box4bet', '0002_auto_20210519_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odd',
            old_name='confirmed',
            new_name='finished',
        ),
    ]
