# Generated by Django 2.2.6 on 2019-10-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='entry_fee',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='competition',
            name='free_entry',
            field=models.BooleanField(default=True),
        ),
    ]
