# Generated by Django 2.2.6 on 2020-02-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionkind',
            name='betfair_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
