# Generated by Django 2.2.6 on 2019-10-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='entry_fee',
            field=models.IntegerField(null=True),
        ),
    ]
