# Generated by Django 2.2.6 on 2019-10-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_auto_20191022_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odd',
            name='prize',
            field=models.FloatField(null=True),
        ),
    ]
