# Generated by Django 2.2.6 on 2019-10-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_betfairsession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betfairsession',
            old_name='session_key',
            new_name='session_token',
        ),
    ]
